class LeelenType:
    OS_TYPE = 1


class APCIType:
    READ_PRIVATE_PROPERTY = bytes([99])
    WRITE_PRIVATE_PROPERTY = bytes([100])


class AckErrorCode:
    IR_LEARN_MAX_CODE = 8
    PARA_ERROR = -126


class AlarmTimeRepeatType:
    EVERY_DAY = "every_day"
    EVERY_MONTH = "every_month"
    EVERY_WEEK = "every_week"
    EVERY_YEAR = "every_year"
    ONCE = "once"
    WORK_DAY = "work_day"


class BIZ_TYPE:
    TYPE_2_0 = "2.0"
    TYPE_3_0 = "3.0"


class BackAudioTypeMark:
    TYPE_MARK_41 = "41"
    TYPE_MARK_44 = "44"
    TYPE_MARK_E3 = "E3"
    TYPE_MARK_E69 = "69"
    TYPE_MARK_E7 = "52"


class CardType:
    AIR_CONDITION = 2
    CURTAIN = 3
    LAMP = 1


class CurtainTripTime:
    TIME_DEFAULT = 10
    TIME_ROBOT_HAND = 5


class Device:
    AC = 5
    AIR_CLEANER = 11
    BOX = 3
    CAR_MULTIMEDIA = 13
    COMPUTER_DESK = 15
    DVD = 4
    FAN = 8
    FOOTBATH = 14
    LIGHT = 10
    PA = 7
    PRO = 6
    SLR = 9
    STB = 1
    TV = 2
    WATER_HEATER = 12


class DeviceMode:
    MODE_FLASH = bytes([1])
    MODE_PING = bytes([0])


class DevicePhysicalType:
    MO_PAI_MINI = 4098


class DeviceReplaceStatus:
    STATUS_ADDRESS_ALLOCATE = 2
    STATUS_ADDRESS_ALLOCATE_FAIL = 242
    STATUS_CONFIG_SYNCHRONIZE = 3
    STATUS_CONFIG_SYNCHRONIZE_FAIL = 243
    STATUS_PRIVATE_DATA_SYNCHRONIZE = 4
    STATUS_PRIVATE_DATA_SYNCHRONIZE_SYNCHRONIZE_FAIL = 244
    STATUS_REPLACE_FAIL = 0
    STATUS_REPLACE_SUCCESS = 1


class DeviceType:
    APP = bytes([1, 0])
    EXTENSION_GATEWAY_HOST = bytes([2, 7])
    HOST = bytes([2, 1])
    LINE_INFRARED_HOST = bytes([2, 8])
    LINUX_EXTENSION_GATEWAY_HOST = bytes([2, 6])
    SERVER = bytes([0, 0])
    WALL = bytes([3, 1])
    WIFI_INFRARED_HOST = bytes([2, 9])
    WIRELESS_HOST = bytes([2, 3])
    WIRELESS_HOST_UPDATE = bytes([2, 16])
    WIRELESS_THREE_GATEWAY = bytes([32, 4])
    WIRELESS_WALL = bytes([3, 2])
    WIRELESS_WALL_M1 = bytes([2, 15])


class DialogType:
    GATEWAY_NOTIFY = 5
    LOGIN_OTHER = 1
    MAIN_ACCOUNT_TRANSFER = 3
    PASSWORD_WRONG = 6
    SHARE_ACCOUNT = 2
    SYNC_GATEWAY_TIME = 4


class EnvironmentType:
    TYPE_HUMIDITY = 2
    TYPE_PM = 0
    TYPE_TEMPERATURE = 1


class FileUseType:
    TYPE_EXPORT_OR_IMPORT = 1
    TYPE_GATEWAY_DB_USE = 0


class FunctionGroupId:
    FUNCTION_CURTAIN_ALL = 930
    FUNCTION_CURTAIN_NEW = 929
    FUNCTION_CURTAIN_OLD = 928
    FUNCTION_DIMMER_ALL = 786
    FUNCTION_DIMMER_NEW = 785
    FUNCTION_DIMMER_OLD = 784
    FUNCTION_FLOOR_HEATING = 2400
    FUNCTION_FRESH_AIR_MODULE = 2432
    FUNCTION_FRESH_AIR_NEW = 2369
    FUNCTION_FRESH_AIR_OLD = 2368
    FUNCTION_IPC_ZW = 2466
    FUNCTION_SCENE = 3600
    FUNCTION_SWITCH = 32


class FunctionType:
    FUNCTION_AC = 12320
    FUNCTION_AC_ACTUATOR = 51232
    FUNCTION_AC_TEMP = 22529
    FUNCTION_ANION_VAL = 18484
    FUNCTION_ARM = 55334
    FUNCTION_ARM_CONDITION = 16267
    FUNCTION_CENTER_AC = 55297
    FUNCTION_CENTER_AC_GROUP = 12369
    FUNCTION_CENTER_AC_ZH = 51256
    FUNCTION_CENTER_AC_ZH_GROUP = 2339
    FUNCTION_CO = 18478
    FUNCTION_COLOR_CONTROL = 55327
    FUNCTION_COLOR_TEMPERATURE_CONTROL = 55339
    FUNCTION_CONNECT_NUM = 16401
    FUNCTION_CURTAIN = 51202
    FUNCTION_CURTAIN_ANGLE = 49211
    FUNCTION_CURTAIN_ROLL_LIMIT = 34866
    FUNCTION_DELAY = 57345
    FUNCTION_DELAY_FOUR_OUTPUT = 57346
    FUNCTION_FLOOR = 12352
    FUNCTION_FLOOR_ACTUATOR = 51234
    FUNCTION_FLOOR_HEATING = 51213
    FUNCTION_FLOOR_HEATING_GROUP = 12352
    FUNCTION_FORMALDEHYDE = 18479
    FUNCTION_FRESH_ACTUATOR = 49185
    FUNCTION_HUMAN_BODY_EXIST_ACT_RL = 18320
    FUNCTION_HUMAN_BODY_EXIST_ACT_RT = 10127
    FUNCTION_HUMIDITY = 16395
    FUNCTION_ILLUMINANCE = 18477
    FUNCTION_IPC = 42890
    FUNCTION_IPC_ZW = 49036
    FUNCTION_IR_LEARN = 47112
    FUNCTION_KTV_485 = 10242
    FUNCTION_LADDER = 51251
    FUNCTION_LEVEL_DIMMER = 51203
    FUNCTION_LEVEL_GEARS = 49156
    FUNCTION_LEVEL_GEARS_GROUP = 12385
    FUNCTION_LOCK_BATTERY = 10177
    FUNCTION_LOCK_CTRL = 46979
    FUNCTION_MUSIC_ARG_CONTROL = 53268
    FUNCTION_MUSIC_PLAY_CONTROL = 55318
    FUNCTION_MUSIC_SCHE_CONTROL = 43029
    FUNCTION_ON_OFF = 51201
    FUNCTION_PM = 18455
    FUNCTION_POWER = 20517
    FUNCTION_POWER_REPORT = 16435
    FUNCTION_PUSH_LINK = 38930
    FUNCTION_RGB_CUR_STATE = 16433
    FUNCTION_SERIAL_PORT_SEND = 38939
    FUNCTION_SMART_BED_MEMORY_SET = 49207
    FUNCTION_SMART_BED_MODE_CTRL = 49205
    FUNCTION_SMART_BED_VIBRATION_CTRL = 51254
    FUNCTION_SMART_SOCKET_DAY_POWER = 22557
    FUNCTION_SMART_SOCKET_HOUR_POWER = 22556
    FUNCTION_SMART_SOCKET_MONTH_POWER = 22558
    FUNCTION_STREAMER_CONTROL = 49196
    FUNCTION_TAMPER = 10179
    FUNCTION_TEMPERATURE = 18442
    FUNCTION_TR_SEND = 38921
    FUNCTION_TYPE_HORIZONTAL = 18304
    FUNCTION_TYPE_ORIENTATION_SENSOR = 10125
    FUNCTION_TYPE_ORIENTATION_SENSOR_OTHER = 18318
    FUNCTION_TYPE_TRIGGER = 10112
    FUNCTION_TYPE_WIRELESS_NOTIFY_TRIGGER = 12166
    FUNCTION_TYPE_WIRELESS_TRIGGER = 12228
    FUNCTION_VOC = 18480
    FUNCTION_WIFI_TR_SEND = 38936
    FUNCTION_ZIGBEE_LOCK_CTRL = 49032


class FunctionValue:
    VALUE_CENTER_AC_ERROR = bytes([255, 255])
    VALUE_CENTER_AC_OFF = bytes([0, 0])
    VALUE_CURTAIN_CLOSE = bytes([0, 0])
    VALUE_CURTAIN_OPEN = bytes([255, 0])
    VALUE_CURTAIN_STOP = bytes([254, 255])
    VALUE_DIMMING_OFF = bytes([0, 0])
    VALUE_DIMMING_ON = bytes([127, 0])
    VALUE_OFF = bytes([0, 0])
    VALUE_ON = bytes([255, 255])
    VALUE_TOGGLE = bytes([254, 255])
    VALUE_VENTILATION_CLOSE = bytes([0])
    VALUE_VENTILATION_LEVEL_FOUR = bytes([254])
    VALUE_VENTILATION_LEVEL_ONE = bytes([1])
    VALUE_VENTILATION_LEVEL_THREE = bytes([3])
    VALUE_VENTILATION_LEVEL_TWO = bytes([2])
    VALUE_VENTILATION_OPEN = bytes([255])


class GatewayTable:
    ACCOUNT_TABLE_NAME = "account_tbl"
    APP_STORAGE_TABLE_NAME = "app_storage_tbl"
    ARM_TABLE_NAME = "arming_tbl"
    DEVICE_STATE_TABLE_NAME = "dev_state_tbl"
    DEVICE_TABLE_NAME = "dev_tbl"
    FLOOR_TABLE_NAME = "floor_tbl"
    IR_KEY_TABLE_NAME = "ir_key_tbl"
    LINKAGE_COND_TABLE_NAME = "linkage_cond_tbl"
    LINKAGE_CTRL_TABLE_NAME = "linkage_ctrl_tbl"
    LINKAGE_TABLE_NAME = "linkage_tbl"
    LOGIC_SERVER_STATE_TABLE_NAME = "logic_srv_state_tbl"
    LOGIC_SERVER_TABLE_NAME = "logic_srv_tbl"
    MSG_STORAGE_COMMON_TABLE_NAME = "msg_storage_common_tbl"
    MSG_STORAGE_LOCK_TABLE_NAME = "msg_storage_lock_tbl"
    PROPERTY_TABLE_NAME = "property_tbl"
    ROOM_TABLE_NAME = "room_tbl"
    SCENE_CTRL_TABLE_NAME = "scene_ctrl_tbl"
    SCENE_TABLE_NAME = "scene_tbl"
    SCHEDULE_STORAGE_TABLE_NAME = "schedule_tbl"
    SENSOR_STATE_TABLE_NAME = "sensor_active_state_tbl"
    SERIAL_PORT_TABLE_NAME = "key_tbl"
    TEMPORARY_USER_TABLE_NAME = "dev_user_tbl"
    TIMER_CONTROL_TABLE_NAME = "timer_ctrl_tbl"
    TIMER_TABLE_NAME = "timer_tbl"


class IconId:
    ICON_ANION = 4800
    ICON_CO_SENSOR = 4448
    ICON_FORMALDEHYDE_SENSOR = 4384
    ICON_HUMIDITY_SENSOR = 4320
    ICON_ID_AIR_CONDITIONER = 256
    ICON_ID_AIR_PURIFIER = 2624
    ICON_ID_AMPLIFIER = 2432
    ICON_ID_AUDIBLE_ALARM = 1664
    ICON_ID_BGM = 1920
    ICON_ID_BOX = 2240
    ICON_ID_CARBON_MONOXIDE = 1216
    ICON_ID_CENTER_AIR_CONDITIONER = 704
    ICON_ID_COMBUSTIBLE_GAS = 1152
    ICON_ID_CURTAIN = 128
    ICON_ID_CURTAIN_ROLL = 4672
    ICON_ID_CUSTOM_CONTROL = 512
    ICON_ID_DIMMER = 64
    ICON_ID_DOUBLE_UNIVERSAL = 3072
    ICON_ID_DVD = 2304
    ICON_ID_ELECTROMAGNETIC = 1600
    ICON_ID_EMERGENCY_BUTTON = 1344
    ICON_ID_FAN = 2496
    ICON_ID_FINGERPRINT_LOCK = 576
    ICON_ID_FLOOD = 1280
    ICON_ID_FLOOR_HEATING = 2112
    ICON_ID_HUMAN_BODY = 896
    ICON_ID_HUMAN_BODY_EXIST = 4864
    ICON_ID_HUMIDITY = 448
    ICON_ID_INFRARED_RADIATION = 960
    ICON_ID_INPUT_OTHER = 1536
    ICON_ID_IPC = 3648
    ICON_ID_IR_LIGHT = 2560
    ICON_ID_JVIPC = 3968
    ICON_ID_LADDER = 4736
    ICON_ID_MAGNETIC = 1024
    ICON_ID_NO_CONFIG = 832
    ICON_ID_ORDINARY_LIGHT = 640
    ICON_ID_OTHER_DEVICE = 768
    ICON_ID_OUTPUT_OTHER = 1856
    ICON_ID_PM = 1984
    ICON_ID_PROJECTOR = 2368
    ICON_ID_PUSH_WINDOW = 1728
    ICON_ID_RAIN = 1472
    ICON_ID_RGB_LIGHT = 3264
    ICON_ID_ROBOT_HAND = 1792
    ICON_ID_ROCKER_SWITCH = 1408
    ICON_ID_RS232_AMPLIFIER = 2752
    ICON_ID_RS232_CUSTOM_CONTROL = 3136
    ICON_ID_RS232_PLAYER = 2816
    ICON_ID_RS232_POWER_SEQUENCER = 2880
    ICON_ID_RS232_PROJECTOR = 2688
    ICON_ID_RS485_AMPLIFIER = 3456
    ICON_ID_RS485_CUSTOM_CONTROL = 3200
    ICON_ID_RS485_PLAYER = 3520
    ICON_ID_RS485_POWER_SEQUENCER = 2944
    ICON_ID_RS485_PROJECTOR = 3392
    ICON_ID_SCENE_PANEL = 3584
    ICON_ID_SENSOR = 2048
    ICON_ID_SINGLE_UNIVERSAL = 3008
    ICON_ID_SMART_BED = 4928
    ICON_ID_SMART_WALL_SOCKET = 3328
    ICON_ID_SMOKE = 1088
    ICON_ID_STB = 2176
    ICON_ID_TELEVISION = 192
    ICON_ID_TEMPERATURE = 384
    ICON_ID_VENTILATION = 320
    ICON_ILLUMINATION_SENSOR = 4544
    ICON_INFRARED_CURTAIN = 3776
    ICON_LIGHT_GROUP = 4032
    ICON_LIGHT_STRIP = 4096
    ICON_ORIENTATION_SENSOR = 4608
    ICON_PM_SENSOR = 4192
    ICON_TEMP_PANEL = 3712
    ICON_TEMP_SENSOR = 4256
    ICON_VOC_SENSOR = 4512


class IrLearnMode:
    MODE_INTO_LEARN = bytes([1])
    MODE_OUT_LEARN = bytes([0])


class IrSendMode:
    MODE_BUFFER_SEND = bytes([1])
    MODE_SEIZE_SEND = bytes([0])


class KeyName:
    AC_WIND_SPEED = "风量"
    ALT = "交替"
    AMP = "缩放+"
    AUTO = "自动"
    BACK = "返回"
    BH = "童锁"
    CHANNEL_ALL_CLOSE = "通道全关"
    CHANNEL_ALL_OPEN = "通道全开"
    CHANNEL_EIGHT_CLOSE = "通道8关"
    CHANNEL_EIGHT_OPEN = "通道8开"
    CHANNEL_FIVE_CLOSE = "通道5关"
    CHANNEL_FIVE_OPEN = "通道5开"
    CHANNEL_FOUR_CLOSE = "通道4关"
    CHANNEL_FOUR_OPEN = "通道4开"
    CHANNEL_LR = "声道"
    CHANNEL_NINE_CLOSE = "通道9关"
    CHANNEL_NINE_OPEN = "通道9开"
    CHANNEL_ONE_CLOSE = "通道1关"
    CHANNEL_ONE_OPEN = "通道1开"
    CHANNEL_SEVEN_CLOSE = "通道7关"
    CHANNEL_SEVEN_OPEN = "通道7开"
    CHANNEL_SIX_CLOSE = "通道6关"
    CHANNEL_SIX_OPEN = "通道6开"
    CHANNEL_TEN_CLOSE = "通道10关"
    CHANNEL_TEN_OPEN = "通道10开"
    CHANNEL_THREE_CLOSE = "通道3关"
    CHANNEL_THREE_OPEN = "通道3开"
    CHANNEL_TWO_CLOSE = "通道2关"
    CHANNEL_TWO_OPEN = "通道2开"
    CHOOSE = "-/--"
    CH_ADD = "频道+"
    CH_MINUS = "频道-"
    DOWN = "下"
    EIGHT = "8"
    FAST_BACK = "快退"
    FAST_PRE = "快进"
    FIVE = "5"
    FOUR = "4"
    HOME = "主页"
    IONS = "负离子"
    LEFT = "左"
    MENU = "菜单"
    MODE = "模式"
    MORE = "更多"
    MUTE = "静音"
    NARROW = "缩放-"
    NEXT_PAGE = "下页"
    NEXT_SONG = "下一曲"
    NINE = "9"
    OK = "确认"
    ONE = "1"
    OUT = "出仓"
    PAUSE = "暂停"
    PLAY = "播放"
    POWER = "电源"
    PRE_PAGE = "上页"
    PRE_SONG = "上一曲"
    REGULAR_TIME = "定时"
    RIGHT = "右"
    SEVEN = "7"
    SIGNAL = "信号源"
    SIGNAL_CHOOSE = "信号源选择"
    SIGNAL_CHOOSE_PA = "HDMI输入输出端口选择"
    SIX = "6"
    SLEEP = "睡眠"
    SMART_SCENE = "智能场景"
    STOP = "停止"
    SUBTITLE = "字幕"
    SWING = "摆风"
    SWITCH_STR = "开关"
    TEMPERATURE_ADD = "温度+"
    TEMPERATURE_MINUS = "温度-"
    THREE = "3"
    TURN_OFF = "关机"
    TURN_ON = "开机"
    TWO = "2"
    UP = "上"
    VOL_ADD = "音量+"
    VOL_ADD_PORT = "音量加"
    VOL_MINUS = "音量-"
    VOL_MINUS_PORT = "音量减"
    WIND_CLASS = "风类"
    WIND_SPEED = "风速"
    ZERO = "0"


class LanProtocolCmd:
    ADD_HOPE_BGM_DEVICE = bytes([142, 5])
    ADD_SERVICE = bytes([29, 3])
    ADD_TEMPORARY_PASSWORD = bytes([37, 3])
    APP_LOGON = bytes([3, 1])
    APP_LOGOUT = bytes([5, 1])
    APP_NOTICE_UPGRADE = bytes([4, 4])
    AUTH_LOGIN = bytes([1, 2])
    AUTH_LOGIN_RESPONSE = bytes([1, 130])
    BGM_PASS_THROUGH = bytes([130, 5])
    BIND_GATEWAY = bytes([1, 3])
    BIND_IPC = bytes([138, 5])
    BIND_XIAO_BAI = bytes([129, 5])
    CANCEL_DEVICE_INVITE = bytes([34, 3])
    CANCEL_GATEWAY_INVITE = bytes([133, 5])
    CHANGE_GATEWAY_IP = bytes([137, 5])
    CONFIG_COMMON_COMMIT = bytes([2, 3])
    CONFIG_CREATE_FLOOR = bytes([13, 3])
    CONFIG_CREATE_LINKAGE = bytes([16, 3])
    CONFIG_CREATE_ROOM = bytes([14, 3])
    CONFIG_CREATE_SCENE = bytes([15, 3])
    CONFIG_CREATE_TIMING = bytes([17, 3])
    CONFIG_FILE_IMPORT = bytes([8, 3])
    CONFIG_GW_BASE_INFO = bytes([22, 3])
    CONFIG_IMPORT_RESULT_NOTIFY_RESPONSE = bytes([28, 131])
    CONFIG_LOCK = bytes([6, 3])
    CONFIG_MOD_FETCH = bytes([5, 3])
    CONFIG_MOD_QUERY = bytes([4, 3])
    CONFIG_REPLACE_DEVICE = bytes([24, 3])
    CONFIG_REPLACE_DEVICE_CANCEL = bytes([25, 3])
    CONFIG_REPLACE_DEVICE_RES = bytes([26, 3])
    CONFIG_SUB_GATEWAY = bytes([33, 3])
    CONFIG_UNLOCK = bytes([7, 3])
    CONFIG_WIFI = bytes([1, 1])
    CREATE_ARM = bytes([40, 3])
    CREATE_INFRARED = bytes([1, 5])
    CREATE_VIRTUAL = bytes([41, 3])
    DELETE_COMMON_MESSAGE = bytes([32, 3])
    DELETE_INFRARED = bytes([2, 5])
    DELETE_SERVICE = bytes([31, 3])
    DELETE_VIRTUAL = bytes([42, 3])
    DEVICE_HINT = bytes([5, 2])
    DEVICE_UPDATE = bytes([6, 2])
    DEVICE_UPGRADE_INFO = bytes([5, 4])
    DEV_CTRL = bytes([3, 2])
    DEV_CTRL_EX = bytes([8, 2])
    DEV_CTRL_RESPONSE = bytes([3, 130])
    DEV_DELETE = bytes([18, 3])
    DEV_INVITE = bytes([19, 3])
    DEV_STATUS = bytes([2, 2])
    FILE_READ = bytes([6, 6])
    FILE_READ_REQ = bytes([4, 6])
    FILE_WRITE = bytes([5, 6])
    FILE_WRITE_REQ = bytes([3, 6])
    FIND_GATEWAY = bytes([1, 1])
    GATEWAY_INVITE = bytes([132, 5])
    GET_485_PROTOCOL_LIST = bytes([36, 3])
    GET_ALARM_SKILLS = bytes([154, 5])
    GET_CLOUD_STATUS = bytes([45, 3])
    GET_CUSTOM_SKILLS = bytes([152, 5])
    GET_DEVICE_LOCATION = bytes([156, 5])
    GET_DEVICE_STATUS = bytes([7, 2])
    GET_DIY_PROTOCOL = bytes([49, 3])
    GET_DIY_PROTOCOL_LIST = bytes([47, 3])
    GET_LOCK_USER_LIST = bytes([44, 3])
    GET_REAL_TEMPORARY_PASSWORD = bytes([43, 3])
    GET_REMOTE_DEBUG = bytes([52, 3])
    GET_SMART_PANEL_ENVIRONMENT_BIND_DATA = bytes([149, 5])
    GET_SMART_PANEL_SCREEN_QUICK_CONTROL = bytes([146, 5])
    HEARTBEAT = bytes([4, 1])
    IR_CREATE_KEY = bytes([4, 5])
    IR_DELETE_KEY = bytes([5, 5])
    IR_SEND_CODE = bytes([6, 5])
    LOCAL_HISTORY_LOCK = bytes([7, 6])
    MANUALLY_ADD_CONDITION = bytes([131, 5])
    NEW_BIND_IPC = bytes([140, 5])
    NEW_UNBIND_IPC = bytes([141, 5])
    PASS_THROUGH_APP_DEVICE = bytes([1, 6])
    RANDOM_CODE = bytes([2, 1])
    REPLACE_GATEWAY = bytes([134, 5])
    SCENE_CTRL = bytes([4, 2])
    SET_DEVICE_LOCATION = bytes([155, 5])
    SET_DIY_PROTOCOL_LIST = bytes([48, 3])
    SET_SMART_PANEL_ENVIRONMENT_BIND_DATA = bytes([150, 5])
    SET_SMART_PANEL_SCREEN_QUICK_CONTROL = bytes([147, 5])
    SMART_PANEL_ADD = bytes([144, 5])
    SMART_PANEL_ENVIRONMENT_SUPPORT_TYPE = bytes([148, 5])
    SMART_PANEL_SCREEN_SUPPORT_TYPE = bytes([145, 5])
    SUBMIT_ALARM_SKILLS = bytes([153, 5])
    SUBMIT_CUSTOM_SKILLS = bytes([151, 5])
    TIME_SYN = bytes([20, 3])
    UNBIND_IPC = bytes([139, 5])
    UPDATE_REMOTE_DEBUG = bytes([51, 3])


class LanProtocolCmdConst:
    ADD_HOPE_BGM_DEVICE_RESPONSE = 34190
    ADD_SERVICE_RESPONSE = 33565
    ADD_SERVICE_RESULT = 798
    ADD_TEMPORARY_PASSWORD_RESPONSE = 33573
    APP_LOGON_RESPONSE = 33027
    APP_LOGOUT_RESPONSE = 33029
    APP_NOTICE_UPGRADE_RESPONSE = 33796
    AUTH_LOGIN_RESPONSE = 33281
    BGM_PASS_THROUGH_RESPONSE = 34178
    BIND_GATEWAY_RESPONSE = 33537
    BIND_IPC_RESPONSE = 34186
    BIND_XIAO_BAI_RESPONSE = 34177
    CANCEL_DEVICE_INVITE_RESPONSE = 33570
    CANCEL_GATEWAY_INVITE_RESPONSE = 34181
    CHANGE_GATEWAY_IP_RESPONSE = 34185
    CONFIG_COMMON_COMMIT_RESPONSE = 33538
    CONFIG_CREATE_FLOOR_RESPONSE = 33549
    CONFIG_CREATE_LINKAGE_RESPONSE = 33552
    CONFIG_CREATE_ROOM_RESPONSE = 33550
    CONFIG_CREATE_SCENE_RESPONSE = 33551
    CONFIG_CREATE_TIMING_RESPONSE = 33553
    CONFIG_FILE_IMPORT_RESPONSE = 33544
    CONFIG_GW_BASE_INFO_RESPONSE = 33558
    CONFIG_IMPORT_RESULT_NOTIFY = 796
    CONFIG_LOCK_RESPONSE = 33542
    CONFIG_MOD_FETCH_RESPONSE = 33541
    CONFIG_MOD_NOTIFY = 771
    CONFIG_MOD_QUERY_RESPONSE = 33540
    CONFIG_REPLACE_DEVICE_CANCEL_RESPONSE = 33561
    CONFIG_REPLACE_DEVICE_RES = 794
    CONFIG_REPLACE_DEVICE_RESPONSE = 33560
    CONFIG_SUB_GATEWAY_RESPONSE = 33569
    CONFIG_UNLOCK_RESPONSE = 33543
    CONFIG_WIFI_RESPONSE = 33025
    CREATE_ARM_RESPONSE = 33576
    CREATE_INFRARED_RESPONSE = 34049
    CREATE_VIRTUAL_RESPONSE = 33577
    DELETE_COMMON_MESSAGE_RESPONSE = 33562
    DELETE_INFRARED_RESPONSE = 34050
    DELETE_SERVICE_RESPONSE = 33567
    DELETE_VIRTUAL_RESPONSE = 33578
    DEVICE_HINT = 517
    DEVICE_HINT_RESPONSE = 33285
    DEVICE_UPDATE = 518
    DEVICE_UPGRADE_INFO_RESPONSE = 33797
    DEVICE_UPGRADE_PROGRESS_RESPONSE = 1027
    DEV_CTRL_EX_RESPONSE = 33288
    DEV_CTRL_RESPONSE = 33283
    DEV_DELETE_RESPONSE = 33554
    DEV_INVITE_RESPONSE = 33555
    DEV_STATUS = 514
    FILE_READ_REQ_RESPONSE = 34308
    FILE_READ_RESPONSE = 34310
    FILE_WRITE_REQ_RESPONSE = 34307
    FILE_WRITE_RESPONSE = 34309
    FORCE_QUIT = 262
    GATEWAY_FEEDBACK_RESPONSE = 1416
    GATEWAY_INVITE_RESPONSE = 34180
    GET_485_PROTOCOL_LIST_RESPONSE = 33572
    GET_ALARM_SKILLS_RESPONSE = 34202
    GET_CLOUD_STATUS_RESPONSE = 33581
    GET_CUSTOM_SKILLS_RESPONSE = 34200
    GET_DEVICE_LOCATION_RESPONSE = 34204
    GET_DEVICE_STATUS_RESPONSE = 33287
    GET_DIY_PROTOCOL_LIST_RESPONSE = 33583
    GET_DIY_PROTOCOL_RESPONSE = 33585
    GET_LOCK_USER_LIST_RESPONSE = 33580
    GET_REAL_TEMPORARY_PASSWORD_RESPONSE = 33579
    GET_REMOTE_DEBUG_RESPONSE = 33588
    GET_SMART_PANEL_ENVIRONMENT_BIND_DATA_RESPONSE = 34197
    GET_SMART_PANEL_SCREEN_QUICK_CONTROL_RESPONSE = 34194
    HEARTBEAT_RESPONSE = 33028
    IR_CREATE_KEY_RESPONSE = 34052
    IR_DELETE_KEY_RESPONSE = 34053
    IR_SYNC_IR_CODE_RESPONSE = 34054
    LOCAL_HISTORY_LOCK_RESPONSE = 34311
    MANUALLY_ADD_CONDITION_RESPONSE = 34179
    NEW_BIND_IPC_RESPONSE = 34188
    NEW_UNBIND_IPC_RESPONSE = 34189
    PASS_THROUGH_APP_DEVICE_RESPONSE = 34305
    RANDOM_CODE_RESPONSE = 33026
    REPLACE_GATEWAY_RESPONSE = 34182
    SCENE_CTRL_RESPONSE = 33284
    SENSOR_STATE = 521
    SET_DEVICE_LOCATION_RESPONSE = 34203
    SET_DIY_PROTOCOL_LIST_RESPONSE = 33584
    SET_SMART_PANEL_ENVIRONMENT_BIND_DATA_RESPONSE = 34198
    SET_SMART_PANEL_SCREEN_QUICK_CONTROL_RESPONSE = 34195
    SMART_PANEL_ADD_RESPONSE = 34192
    SMART_PANEL_ENVIRONMENT_SUPPORT_TYPE_RESPONSE = 34196
    SMART_PANEL_SCREEN_SUPPORT_TYPE_RESPONSE = 34193
    SUBMIT_ALARM_SKILLS_RESPONSE = 34201
    SUBMIT_CUSTOM_SKILLS_RESPONSE = 34199
    TIME_SYN_RESPONSE = 33556
    UNBIND_IPC_RESPONSE = 34187
    UPDATE_REMOTE_DEBUG_RESPONSE = 33587


class LockAlertType:
    TYPE_DOOR_BELL = bytes([1, 2])
    TYPE_DOOR_PRYING = bytes([5, 3])
    TYPE_ILLEGAL_CREDIT_CARD_UNLOCK = bytes([3, 3])
    TYPE_ILLEGAL_FINGER_UNLOCK = bytes([1, 3])
    TYPE_ILLEGAL_PASSWORD_UNLOCK = bytes([2, 3])
    TYPE_ILLEGAL_UNLOCK = bytes([0, 3])
    TYPE_LOCK_PRYING = bytes([4, 3])


class LockConfigTime:
    CONFIG_DEVICE_TIME = 600
    CONFIG_GW_TIME = 100


class LockFailMsgType:
    TYPE_LOCKED = "locked"
    TYPE_SYNC = "sync"


class LockOperateType:
    TYPE_OPERATE_DEVICE = 1
    TYPE_OPERATE_GATEWAY = 0


class LockPushLevel:
    LEVEL_ALARM = 1
    LEVEL_MSG = 3
    LEVEL_NOTIFY = 2


class LockPushMode:
    MODE_MSG = 2
    MODE_NET = 0
    MODE_PHONE = 1
    MODE_SYSTEM_NOTIFY_AND_PASS_THROUGH = 4


class LockStatusValue:
    STATUS_REGISTER_FAIL = bytes([1, 0])
    STATUS_REGISTER_SUCCESS = bytes([1, 1])
    STATUS_UNLOCK_FAIL = bytes([0, 0])
    STATUS_UNLOCK_SUCCESS = bytes([255, 255])


class LockValue:
    DEFAULT_MEMBER_VALUE = bytes([0, 0, 255, 255])
    OPEN_LOCK_VALUE = bytes([255, 255, 255, 255])
    OPEN_ZIGBEE_LOCK_VALUE = bytes([255, 255])
    REGISTER_LOCK_VALUE = bytes([0, 0, 1, 0])
    UNLOCK_BY_FINGER_PRINT_BIG_VALUE = bytes([255, 255, 0, 3])
    UNLOCK_BY_FINGER_PRINT_LITTLE_VALUE = bytes([0, 0, 0, 3])
    UNLOCK_BY_PASSWORD_BIG_VALUE = bytes([255, 255, 0, 4])
    UNLOCK_BY_PASSWORD_LITTLE_VALUE = bytes([0, 0, 0, 4])
    UNLOCK_BY_SWIPE_BIG_VALUE = bytes([255, 255, 0, 5])
    UNLOCK_BY_SWIPE_LITTLE_VALUE = bytes([0, 0, 0, 5])


class LogicDeviceType:
    ARM = 259
    AVE_TEMP_PANEL = 258
    COLOR_DIMMABLE_LIGHT = 54
    COLOR_DIMMER_SWITCH = 55
    DIY_CENTER_AC = 778
    DIY_FLOOR_HEARTING = 779
    DIY_REFRESH_AIR = 780
    DREAM_CURTAIN = 574
    HUMAN_BODY_EXIST = 600
    LADDER_CONTROL = 158
    LINE_GATEWAY_INFRARED = 773
    MUL_DIMMING_DELETE = 84
    PROXIMITY_SENSING = 83
    TWO_LINE_GATEWAY = 769
    TYPE_AC_ACTUATOR = 773
    TYPE_AC_CONTROL = 770
    TYPE_AC_FRESH = 777
    TYPE_ANION = 85
    TYPE_BACK_AUDIO_BGM = 147
    TYPE_CARBON_DIOXIDE_SENSOR = 596
    TYPE_CENTER_AIR_CONDITIONER = 146
    TYPE_COLOR_TEMPERATURE_LIGHT = 568
    TYPE_CURTAIN = 58
    TYPE_DIMMING_LIGHT = 49
    TYPE_DIMMING_LIGHT_ZIGBEE = 561
    TYPE_FLOOR = 776
    TYPE_FLOOR_ACTUATOR = 775
    TYPE_FLOOR_CONTROL = 772
    TYPE_FLOOR_HEATING_NEW = 150
    TYPE_FORMALDEHYDE_SENSOR = 597
    TYPE_FRESH_ACTUATOR = 774
    TYPE_FRESH_CONTROL = 771
    TYPE_HUMIDITY_SENSOR = 66
    TYPE_ILLUMINATION_SENSOR = 579
    TYPE_INFRARED_AC = 242
    TYPE_INFRARED_AGENT = 245
    TYPE_INFRARED_CUSTOMIZE = 243
    TYPE_INFRARED_TRANSFER = 255
    TYPE_INFRARED_TV = 241
    TYPE_INPUT = 5
    TYPE_IPC = 154
    TYPE_KTV_485_CENTER_AIR_CONDITIONER = 157
    TYPE_LIGHT = 2
    TYPE_LIGHT_STRIP = 569
    TYPE_ORIENTATION_SENSOR = 599
    TYPE_OTHER = -1
    TYPE_OUT_PUT = 3
    TYPE_PM_SENSOR = 75
    TYPE_PORT_CENTRAL_CONTROL = 257
    TYPE_POWER_SENSOR = 601
    TYPE_REFRESH_AIR = 152
    TYPE_RGB_LIGHT = 566
    TYPE_RGB_TEMPERATURE_LIGHT = 567
    TYPE_SCENE_PANEL = 224
    TYPE_SENSOR = -2
    TYPE_SHADE_CONTROLLER = 59
    TYPE_SMART_LOCK = 149
    TYPE_SWITCH_CONTROL = 1
    TYPE_SWITCH_MULTI_MODE = 512
    TYPE_TEMPERATURE_SENSOR = 65
    TYPE_TEMP_HUMIDITY_SENSOR = 595
    TYPE_VENTILATION_SYSTEM = 148
    TYPE_VOC_SENSOR = 598
    TYPE_WIFI_INFRARED = 244
    TYPE_WIRELESS_ACOUSTO_OPTIC = 594
    TYPE_WIRELESS_ASSISTANCE_BUTTON = 590
    TYPE_WIRELESS_CO_SENSOR = 592
    TYPE_WIRELESS_CURTAIN = 570
    TYPE_WIRELESS_DOOR_SENSOR = 586
    TYPE_WIRELESS_GAS_SENSOR = 593
    TYPE_WIRELESS_HUMIDITY_SENSOR = 578
    TYPE_WIRELESS_INFRARED_SENSOR = 576
    TYPE_WIRELESS_LIGHT = 514
    TYPE_WIRELESS_ROLL_CURTAIN = 573
    TYPE_WIRELESS_SMOKE_SENSOR = 581
    TYPE_WIRELESS_SWITCH_CONTROL = 513
    TYPE_WIRELESS_TEMPERATURE_SENSOR = 577
    TYPE_WIRELESS_WATER_IMMERSION_SENSOR = 591
    WIFI_GATEWAY_INFRARED = 774
    WIFI_LOCK = 8193
    WIRELESS_GATEWAY = 770
    WIRELESS_INPUT_SWITCH = 517
    WIRELESS_OUT_PUT_CURTAIN = 571
    WIRELESS_OUT_PUT_SWITCH = 515
    ZIGBEE_AC_GATEWAY_AC = 782
    ZIGBEE_AC_GATEWAY_REFRESH_AIR = 783
    ZIGBEE_CENTER_AC = 658
    ZIGBEE_FLOOR_HEARTING = 662
    ZIGBEE_LOCK = 665
    ZIGBEE_REFRESH_AIR = 664
    ZIGBEE_SMART_BED = 781
    ZIGBEE_SMART_WALL_SOCKET = 518


class MediaSourceArgType:
    MEDIA_SOURCE_CLOUD = 3
    MEDIA_SOURCE_LOCAL = 0
    MEDIA_SOURCE_NO_CHANGE = 7


class MediaSource:
    STRING_DEFAULT = "default"
    STRING_MUTE = "mute"
    STRING_WARN = "warn"


class MediaSourceType:
    TYPE_CLOUD = 1
    TYPE_CURRENT_CLOUD = 5
    TYPE_CURRENT_LOCAL = 4
    TYPE_FAV_CLOUD = 3
    TYPE_FAV_LOCAL = 2
    TYPE_LOCAL = 0


class PanelType:
    TYPE_NORMAL = 0
    TYPE_P1 = 2


class PassThroughType:
    TA = bytes([1])
    TB = bytes([2])
    TN = bytes([0])


class PermissionCode:
    CALL_BACK_PERMISSION_NO_NEED_CODE = 5
    CALL_BACK_PERMISSION_REQUEST_CODE = 4
    CALL_BACK_RESULE_CODE_FAILURE = 3
    CALL_BACK_RESULT_CODE_SUCCESS = 2
    PERMISSION_REQUEST_CODE = 1


class PhysicalDeviceType:
    AC_FRESH_ACTUATOR = 610
    AC_FRESH_ACTUATOR_SPECIAL = 531
    AC_GATEWAY_THREE_PANEL = 1155
    AIR_ENVIRONMENT_DETECTOR = 642
    ANION_485 = 645
    BACK_AUDIO_BGM = 1057
    BATTERY_CURTAIN = 598
    CENTER_AIR_CONDITIONING = 1088
    CENTER_AIR_CONDITIONING_FRESH = 1091
    CLOTHES_HANGER = 8208
    CURTAIN_SENSOR_UPDATE = 689
    DIMMING_LIGHT_SWITCH_PANEL = 96
    DIY_PROTOCOL_MODULE = 1154
    DOCKING_PANEL_P = 1095
    DOUBLE_CURTAIN_CONTROL_PANEL = 81
    DOUBLE_DIMMING_MODULE = 100
    EMBEDDED_AIR_ENVIRONMENT_DETECTOR = 643
    EMBEDDED_CURTAIN_SENSOR = 644
    FALL_SENSOR = 2012
    FLOOR_HEART_ACTUATOR = 641
    FLOOR_HEATING_DOCKING_MODULE = 1090
    FLUORITE_CAMERA = 1064
    FOUR_MULTI_FUNCTION_CONTROL_PANEL = 257
    FOUR_OUTPUT_MODEL = 160
    FOUR_SWITCH_PANEL = 4
    FRESH_AIR_ACTUATOR = 128
    FRESH_AIR_DOCKING_MODULE = 1089
    HA_GENERAL_EQUIPMENT = 674
    HOPE_BGM = 1068
    HUMAN_BODY_EXIST = 676
    INFRARED_TRANSPONDER = 176
    KTV_485_CENTER_AIR_CONDITIONER = 1094
    LCD_CONTROL_PANEL = 416
    LINE_AC_FRESH_ACTUATOR = 98
    LINE_DIY_PROTOCOL_MODULE = 1092
    LINE_FLOOR_HEART_ACTUATOR = 130
    LINE_FOUR_SWITCH_PANEL = 51000
    LINE_GATEWAY_INFRARED = 773
    LINE_TEMPERATURE_CONTROL_PANEL = 435
    LOCK_SWITCH_PANEL = 192
    MO_PAI_GATEWAY = 775
    MO_PAI_LITE = 1025
    MO_PAI_MINI = 1026
    MO_PAI_PRO_H1 = 1027
    MO_PAI_PRO_H2 = 1028
    MO_PAI_PRO_H3 = 1029
    MUL_DIMMING_MODULE = 99
    ONE_SWITCH_PANEL = 1
    OPEN_CONTROL_PANEL = 1093
    PM_PANEL = 1058
    SINGLE_CURTAIN_CONTROL_PANEL = 80
    SINGLE_FIRE_SWITCH_PANEL_ONE = 528
    SINGLE_FIRE_SWITCH_PANEL_THREE = 530
    SINGLE_FIRE_SWITCH_PANEL_TWO = 529
    SIX_INPUT_MODEL = 161
    SIX_MULTI_FUNCTION_CONTROL_PANEL = 258
    SMART_REMOTE = 106011
    SONOS_BGM = 1063
    SPEAKER_BGM = 1065
    TEMPERATURE_CONTROL_PANEL = 1458
    THREE_SWITCH_PANEL = 3
    TING_PANEL_P = 1096
    TWO_DOUBLE_KEY_CONTROL_PANEL = 336
    TWO_LINE_GATEWAY = 769
    TWO_LINE_ONE_SWITCH_PANEL_THREE_CONFIG = 11
    TWO_LINE_TWO_SWITCH_PANEL_TWO_CONFIG = 13
    TWO_LINE_WIRELESS_THREE_SWITCH_PANEL_ONE_CONFIG = 14
    TWO_SWITCH_PANEL = 2
    TYPE_AVE = 865
    UDA_BGM = 1066
    VEDIO_AND_AUDIO_CENTER_CONTROL = 1062
    WHITE_ROBOT = 1024
    WIFI_GATEWAY_INFRARED = 774
    WIFI_INFRARED = 1060
    WIRELESS_CURTAIN_MOTOR = 594
    WIRELESS_CURTAIN_ROLL_MOTOR = 597
    WIRELESS_DOUBLE_CURTAIN_SWITCH_PANEL = 1457
    WIRELESS_FOUR_MULTI_FUNCTION_CONTROL_PANEL = 1281
    WIRELESS_FOUR_SWITCH_PANEL = 516
    WIRELESS_GATEWAY = 770
    WIRELESS_GATEWAY_A = 771
    WIRELESS_GATEWAY_UPDATE = 776
    WIRELESS_LCD_CONTROL_PANEL = 1440
    WIRELESS_ONE_SWITCH_PANEL = 513
    WIRELESS_ONE_SWITCH_PANEL_ONE_CONFIG = 521
    WIRELESS_ONE_SWITCH_PANEL_THREE_CONFIG = 523
    WIRELESS_ONE_SWITCH_PANEL_TWO_CONFIG = 522
    WIRELESS_SINGLE_CURTAIN_CONTROL_PANEL = 1456
    WIRELESS_THREE_SWITCH_PANEL = 515
    WIRELESS_THREE_SWITCH_PANEL_ONE_CONFIG = 526
    WIRELESS_TWO_SWITCH_PANEL = 514
    WIRELESS_TWO_SWITCH_PANEL_ONE_CONFIG = 524
    WIRELESS_TWO_SWITCH_PANEL_TWO_CONFIG = 525
    WISE_BGM = 1067
    ZHONG_HONG_CENTER_AC = 1059
    ZIGBEE_0_10V = 616
    ZIGBEE_485_DOCKING_MODEL = 1153
    ZIGBEE_COLOR_TEMPERATURE_LIGHT = 612
    ZIGBEE_DIMMING_LIGHT_SWITCH_PANEL = 608
    ZIGBEE_FINGERPRINT_LOCK_02 = 706
    ZIGBEE_FINGERPRINT_LOCK_03 = 704
    ZIGBEE_FINGERPRINT_LOCK_06 = 709
    ZIGBEE_FINGERPRINT_LOCK_07 = 708
    ZIGBEE_FINGERPRINT_LOCK_08 = 707
    ZIGBEE_FINGERPRINT_LOCK_11 = 711
    ZIGBEE_FOUR_INPUT_OUTPUT_MODEL = 675
    ZIGBEE_HEART_COOL = 614
    ZIGBEE_HEART_COOL_COLOR = 613
    ZIGBEE_LIGHT_STRIP = 615
    ZIGBEE_RGB_LIGHT = 609
    ZIGBEE_RGB_TEMPERATURE_LIGHT = 611
    ZIGBEE_SIX_FREEP_PANEL = 1282
    ZIGBEE_SMART_WALL_SOCKET = 520
    ZIGBEE_SMART_WALL_SOCKET_UPDATE = 527
    ZIGBEE_THREE_HIDDEN_SWITCH_PANEL = 519
    ZIGBEE_TWO_HIDDEN_SWITCH_PANEL = 518


class PropertyId:
    ANION_WORK_MODE = bytes([1, 161])
    ARM_PROPERTY = 160
    AVE_PROPERTY_ID = 161
    AVE_PROPERTY_MAC = 134
    BACK_MUSIC_ACCREDIT_STATUS = 172
    COLOR_TEMPERATURE_AREA = 160
    CONTROL_TYPE = 161
    CREATE_SERVER_NUM_ID = 138
    CREATE_SERVER_PROPERTY_ID = 139
    CURTAIN_MOTOR = bytes([1, 163])
    CURTAIN_MOTOR_LIMIT = bytes([1, 165])
    CURTAIN_MOTOR_SPEED = 164
    CURTAIN_TRIP_ID = 160
    DAMPER_SWITCH = 164
    DAMPER_SWITCH_LITE = 168
    DEVICE_IP = 161
    DEVICE_LAYOUT = 128
    DEVICE_MAC = 160
    DEVICE_TYPE = 179
    DID = 171
    DID_GENERATE_RULE = 177
    DIMMER_STEP_ID = 161
    DIRECT_DID = 170
    FLOOR_LOW_TEMP = 163
    FLOOR_LOW_TEMP_LITE = 167
    GATEWAY_MAC = 164
    GATEWAY_NETWORK_ID = 162
    GW_ADDR_PROPERTY_ID = 1
    GW_LITTLE_VER_PROPERTY_ID = 2
    GW_VER_PROPERTY_ID = 0
    HIDDEN_SWITCH_TYPE = 162
    HUMAN_BODY_DETECTION_ZONE = 162
    HUMAN_BODY_INDICATOR_SWITCH = 161
    HUMAN_BODY_SENSITIVITY = 160
    IPC_EXT = 163
    IPC_MANUFACTURER = 164
    IPC_PROPERTY = 160
    IPC_TYPE = 161
    IPC_TYPE_NUM = 161
    IR_ADDRESS_PROPERTY_ID = 144
    IR_CODE_EXIST = 165
    IR_CODE_PROPERTY_ID = 145
    KTV_CONN_PARAM = 160
    KTV_PROPERTY_1 = 161
    KTV_PROPERTY_10 = 179
    KTV_PROPERTY_11 = 181
    KTV_PROPERTY_12 = 183
    KTV_PROPERTY_13 = 185
    KTV_PROPERTY_14 = 187
    KTV_PROPERTY_15 = 189
    KTV_PROPERTY_2 = 163
    KTV_PROPERTY_3 = 165
    KTV_PROPERTY_4 = 167
    KTV_PROPERTY_5 = 169
    KTV_PROPERTY_6 = 171
    KTV_PROPERTY_7 = 173
    KTV_PROPERTY_8 = 175
    KTV_PROPERTY_9 = 177
    LIGHT_PATTERN = 136
    LOCK_CER_CODE = 160
    LOCK_SUPPORT_SYNC_USER = 161
    M1_WAKE_WORD = 178
    MAC = 178
    MAX_BRIGHT_ID = 163
    MOPAI_TEMP_COMPENSATION = 166
    MULTI_KEY_RELATION_BIND_ID = 121
    MUL_DIMMER_ID = 164
    MUL_DIMMER_SETTING_ID = 165
    ONE_PIN_ID = 162
    PROFILE_ID = 180
    PROTOCOL_PROPERTY_ID = bytes([0, 162])
    PROXIMITY_SENSING = 162
    RELATE_ANION = 173
    RELATE_HUMIDITY = 169
    RELATE_PM = 165
    RELATE_TEMPERATURE = 164
    RELATION_BIND_ID = 128
    SCENE_ADD_DEVICE_NUM_ID = 140
    SELECTED_PROTOCOL_ID = 162
    SERIAL_PORT_DEVICE_TYPE = 160
    SUB_GATEWAY_IP = 163
    TEMP_COMPENSATION = 162
    TEMP_CONTROL_PM = 160
    TEMP_PROXIMITY_SENSING = 161
    TWO_PIN_ID = 161
    UNIQUELY_IDENTIFIES = 176
    WIFI_IR_DEVICE_TYPE = 160
    WIFI_IR_MAC_SSID = bytes([0, 164])
    WIFI_IR_REMOTE_ID = 161
    WIRELESS_BRIGHT_ID = 160
    WIRELESS_SSID = 165
    ZIGBEE_485_PROTOCOL_ID = 161
    ZIGBEE_OUT_PUT_ID = 160


class ProtocolDefault:
    DEFAULT_LAN_SERVER_ID = bytes([255, 255])
    DEFAULT_WAN_SERVER_ID = bytes([0, 0])
    LAN_ENCRYPT = bytes([1, 0])
    LAN_NO_ENCRYPT = bytes([0, 0])
    PROTOCOL_VER_LAN = bytes([1, 0])
    PROTOCOL_VER_WAN = bytes([1, 3])


class ProtocolType:
    TYPE_CHANG_HONG = 1024
    TYPE_DAIKIN = 4
    TYPE_DEMRY_GATEWAY = 8192
    TYPE_DRAUGHT_FAN = 4096
    TYPE_FU_SHI_TONG = 16
    TYPE_GAO_BIAO = 2
    TYPE_HITACHI = 2
    TYPE_HITACHI_CPC = 512
    TYPE_IRACC = 1
    TYPE_LAN_SHE = 2
    TYPE_MCKINVILLE = 2048
    TYPE_NO_SUPPORT = 0
    TYPE_PANASONIC = 8
    TYPE_YUE_KE = 64
    TYPE_YUE_KE_OTHER = 128
    TYPE_ZHI_GAO = 32
    TYPE_ZHONGHONG_INDOOR = 32768
    TYPE_ZHONG_HONG = 8


class PushMsgType:
    BIND = 2
    FAMILLY_CHANGE = 9
    FEEDBACK_REPLY = 10
    GET_INFO = 6
    GET_IPC_LIST = 11
    MAIN_ACCOUNT_TRANSFER = 7
    NOTIFY = 12
    SERVER_NOTIFY = 8
    SHARE = 5


class PushType:
    TYPE_HW = 1
    TYPE_JG = 3
    TYPE_WAN = 0
    TYPE_XM = 2


class RoomBgImageId:
    BALCONY = 9
    BATHROOM = 8
    DEFAULT_ROOM = 0
    GARAGE = 10
    GUEST_LYING = 3
    KITCHEN = 5
    LIVING_ROOM = 1
    MASTER_BEDROOM = 2
    RESTAURANT = 6
    STUDY = 4
    VIDEO_ROOM = 7
    WAREHOUSE = 11


class ScanQrCodeType:
    TYPE_AUTHORIZATION_LOGIN = 1
    TYPE_IPC = 0


class SceneIconId:
    ICON_ID_ALL_CLOSE = 32896
    ICON_ID_ALL_OPEN = 32832
    ICON_ID_AUDIO_VIDEO = 33536
    ICON_ID_AWAY_FROM_HOME = 33024
    ICON_ID_BATHROOM = 49552
    ICON_ID_BATHROOM_CONTROL = 49536
    ICON_ID_BEDROOM = 49424
    ICON_ID_BEDROOM_CONTROL = 49408
    ICON_ID_CHILDREN_ROOM = 49808
    ICON_ID_CHILDREN_ROOM_CONTROL = 49792
    ICON_ID_CLOAK_ROOM = 49744
    ICON_ID_CLOAK_ROOM_CONTROL = 49728
    ICON_ID_CORRIDOR = 50064
    ICON_ID_CORRIDOR_CONTROL = 50048
    ICON_ID_CUSTOM = 50128
    ICON_ID_CUSTOMIZE = 32768
    ICON_ID_CUSTOM_CONTROL = 50112
    ICON_ID_DINING = 33344
    ICON_ID_ENTERTAINMENT = 33472
    ICON_ID_ENTRANCE = 49616
    ICON_ID_ENTRANCE_CONTROL = 49600
    ICON_ID_GET_UP = 33088
    ICON_ID_GO_HOME = 32960
    ICON_ID_GUEST = 33280
    ICON_ID_HOME_THEATER = 49936
    ICON_ID_HOME_THEATER_CONTROL = 49920
    ICON_ID_IN = 49232
    ICON_ID_IN_CONTROL = 49216
    ICON_ID_JOB = 33216
    ICON_ID_KITCHEN = 49488
    ICON_ID_KITCHEN_CONTROL = 49472
    ICON_ID_LEISURE = 33408
    ICON_ID_LIVING = 49360
    ICON_ID_LIVING_CONTROL = 49344
    ICON_ID_NIGHT = 33600
    ICON_ID_NO = 0
    ICON_ID_OUT = 49168
    ICON_ID_OUT_CONTROL = 49152
    ICON_ID_READ = 33664
    ICON_ID_RECREATION_ROOM = 49872
    ICON_ID_RECREATION_ROOM_CONTROL = 49856
    ICON_ID_REMOVE = 49296
    ICON_ID_REMOVE_CONTROL = 49280
    ICON_ID_RESTAURANT = 50000
    ICON_ID_RESTAURANT_CONTROL = 49984
    ICON_ID_SLEEP = 33152
    ICON_ID_TOILET = 49680
    ICON_ID_TOILET_CONTROL = 49664


class SearchGatewayType:
    TYPE_ADD_SUB_LINE_INFRARED = 9
    TYPE_ADD_SUB_TWO_LINE = 4
    TYPE_ADD_SUB_WIFI_INFRARED = 8
    TYPE_ADD_SUB_WIRELESS = 3
    TYPE_ALL = 0
    TYPE_LINE_INFRARED = 6
    TYPE_MAIN_GATEWAY = -1
    TYPE_REPLACE = 5
    TYPE_WIFI_INFRARED = 7
    TYPE_WIRELESS = 2


class SkillActionType:
    CHILDREN_STORY = "children_story"
    DEVICE_CTRL = "device_ctrl"
    HEALTH_BY_CTRL = "health_by_ctrl"
    MUSIC = "music"
    MUSIC_BY_CTRL = "music_by_ctrl"
    NEWS = "news"
    ROUTE = "route"
    SCENE_CTRL = "scene_ctrl"
    TXT_CTRL = "txt_ctrl"
    WEATHER = "weather"


class SmartLockMsgType:
    TYPE_ALERT = 12226
    TYPE_BATTERY = 10177
    TYPE_OPEN_DOOR = 46979
    TYPE_ZIGBEE_OPEN_DOOR = 49032


class SoundType:
    TYPE_DEFAULT = 1
    TYPE_MUTE = 0
    TYPE_WARN = 2


class StorageContentCode:
    FINGERPRINT_LOCK_PASSWORD = 1
    FINGERPRINT_LOCK_USER_INFO = 0


class StructVersionAck:
    ACK_FAIL = 0
    ACK_HIGH_VERSION = 11
    ACK_LOW_VERSION = 10
    ACK_SUCCESS = 1


class SubGatewayAddress:
    FIFTH_SUB_GATEWAY = 40960
    FIRST_SUB_GATEWAY = 8192
    FOURTH_SUB_GATEWAY = 32768
    MAX_SUB_GATEWAY = 57344
    SECOND_SUB_GATEWAY = 16384
    SIXTH_SUB_GATEWAY = 49152
    THIRD_SUB_GATEWAY = 24576


class SystemSceneAddress:
    FULLY_CLOSE = 61694
    FULLY_OPEN = 61695


class TONE_QUALITY:
    HQ = 2
    LQ = 1
    SQ = 3


class TableOperateType:
    TYPE_DELETE = "del"
    TYPE_INSERT = "ins"
    TYPE_UPDATE = "upd"


class TcpLanLogonFailType:
    PASSWORD = 2
    UNICAST_ERR = 0
    USERNAME = 1


class TcpWanReturnCode:
    FAIL = 2
    LOGON_WRONG = -124
    MEMORY = 4
    NOT_SUPPORT = 3
    PSW_WRONG = 6
    RELOGON = 7
    SUCC = 1
    TRANSFER = 5


class TimeLength:
    CONNECT_TIMEOUT = 5000
    CURTAIN_DEFAULT_TIME = 10
    HEARTBEAT_INTERVAL = 20
    HEARTBEAT_INTERVAL_LAN = 5
    HEARTBEAT_INTERVAL_SERVICE = 20000
    MULTICAST_SOTIMEOUT = 2000


class TimerCtrlType:
    TYPE_LINKAGE = 2
    TYPE_SCENE = 1
    TYPE_SERVER = 0
    TYPE_SINGLE_DEVICE = 4


class TvKeyId:
    BOX_CHANNEL_ADD = 10
    BOX_CHANNEL_MINUS = 11
    BOX_MUTE = 4
    BOX_POWER = 3
    BOX_VOLUME_ADD = 8
    BOX_VOLUME_MINUS = 9
    TV_MODE = 5
    TV_MUTE = 2
    TV_NUMBER_EIGHT = 19
    TV_NUMBER_FIVE = 16
    TV_NUMBER_FOUR = 15
    TV_NUMBER_NINE = 20
    TV_NUMBER_ONE = 12
    TV_NUMBER_SEVEN = 18
    TV_NUMBER_SIX = 17
    TV_NUMBER_THREE = 14
    TV_NUMBER_TWO = 13
    TV_NUMBER_ZERO = 21
    TV_POWER = 1
    TV_VOLUME_ADD = 6
    TV_VOLUME_MINUS = 7


class TypeValue:
    SERIAL_PORT_CUSTOM_REMOTE = 0
    SERIAL_PORT_PA_REMOTE = 4
    SERIAL_PORT_PLAYER_REMOTE = 2
    SERIAL_PORT_POWER_REMOTE = 3
    SERIAL_PORT_PRO_REMOTE = 1
    SERIAL_PORT_VEDIO_REMOTE = 5
    WIFI_IR_REMOTE_CUSTOM = 254
    WIFI_IR_REMOTE_CUSTOM_AC = 5
    WIFI_IR_REMOTE_CUSTOM_AIR_CLEAN = 11
    WIFI_IR_REMOTE_CUSTOM_BOX = 3
    WIFI_IR_REMOTE_CUSTOM_DVD = 4
    WIFI_IR_REMOTE_CUSTOM_FAN = 8
    WIFI_IR_REMOTE_CUSTOM_LIGHT = 10
    WIFI_IR_REMOTE_CUSTOM_PA = 7
    WIFI_IR_REMOTE_CUSTOM_PRO = 6
    WIFI_IR_REMOTE_CUSTOM_STB = 1
    WIFI_IR_REMOTE_CUSTOM_TV = 2


class UdaTypeMark:
    TYPE_55T = 85
    TYPE_55T_AND_BLUETOOTH = 86
    TYPE_55T_NOT_BLUETOOTH = 87
    TYPE_8028 = 24
    TYPE_BLUETOOTH = 64
    TYPE_CEILING_HOST_T3 = 113
    TYPE_CENTRAL_CONTROL_HOST = 14
    TYPE_DOORBELL = 118
    TYPE_I31 = 124
    TYPE_I32 = 125
    TYPE_I5_AND_BLUETOOTH = 88
    TYPE_I5_NOT_BLUETOOTH = 89
    TYPE_I7 = 96
    TYPE_INFRARED_LEARNER = 117
    TYPE_RESERVE_Y12 = 123
    TYPE_W5 = 115
    TYPE_WIRE = 16
    TYPE_WIRELESS = 12
    TYPE_WIRE_AND_AUX = 13
    TYPE_Y1 = 119
    TYPE_Y2 = 116
    TYPE_Y4 = 114
    TYPE_Y6 = 121
    TYPE_Y8 = 122


class UploadPhotoStatus:
    FAILURE = -1
    NO_UPLOAD = 0
    SUCCEED = 2
    UPLOADING = 1


class VirtualStateIconId:
    ICON_AT_HOME_CONTROL = 3840
    ICON_AT_HOME_EDIT = 3856
    ICON_AT_HOME_TYPE = 3872
    ICON_CLOSE_CONTROL = 3852
    ICON_CLOSE_EDIT = 3868
    ICON_CLOSE_TYPE = 3884
    ICON_GET_UP_CONTROL = 3846
    ICON_GET_UP_EDIT = 3862
    ICON_GET_UP_TYPE = 3878
    ICON_LEAVE_HOME_CONTROL = 3842
    ICON_LEAVE_HOME_EDIT = 3858
    ICON_LEAVE_HOME_TYPE = 3874
    ICON_OPEN_CONTROL = 3850
    ICON_OPEN_EDIT = 3866
    ICON_OPEN_TYPE = 3882
    ICON_OUT_CONTROL = 3848
    ICON_OUT_EDIT = 3864
    ICON_OUT_TYPE = 3880
    ICON_SLEEP_CONTROL = 3844
    ICON_SLEEP_EDIT = 3860
    ICON_SLEEP_TYPE = 3876


class VoiceMetaType:
    CUSTOM_SKILL = "custom_skill"
    PERSONALIZED_QA = "personalized_qa"
    REMINDER_ALARM = "reminder_alarm"
    REMINDER_SCHEDULE = "reminder_schedule"
    REPORT_PUNCTUALLY = "report_punctually"


class VoiceSkillOperateType:
    ADD = "add"
    DEL = "del"
    MOD = "mod"


class VoiceType:
    ALARM_REMINDER = 4
    CUSTOM_SKILL = 1
    PERSONALIZED_QA = 2
    REPORT_PUNCTUALLY = 5
    SCHEDULE_REMINDER = 3


class WanGatewayReplaceState:
    LOAD_OLD_CONFIG = 4
    REPLACE_COMPLETE = 15
    REPLACE_FAIL = 3


class WanProtocolCmd:
    APP_LOGON = bytes([2, 98])
    CHECK_GATEWAY_NEED_UPGRADE = bytes([16, 98])
    GATEWAY_ONLINE = bytes([15, 98])
    GATEWAY_REPLACE_STATE = bytes([9, 98])
    GET_GATEWAY_SERVER = bytes([3, 98])
    HEARTBEAT = bytes([4, 96])
    LOGOUT_GATEWAY = bytes([4, 98])
    PASS_THROUGH = bytes([0, 98])
    PUSH_MSG = bytes([0, 99])
    REPEAT_LOGIN = bytes([12, 96])


class Zigbee485AcProtocolType:
    TYPE_DAIKIN = 3
    TYPE_FU_SHI_TONG = 5
    TYPE_GREE = 7
    TYPE_HITACHI = 2
    TYPE_IRACC = 1
    TYPE_ZHI_GAO = 6
    TYPE_ZHONG_HONG = 4


class Zigbee485FloorHeatingProtocolType:
    TYPE_HAILIN = 1


class Zigbee485FreshAirProtocolType:
    TYPE_DEPULAITAI = 1
    TYPE_LOWNSWELL = 2


class Zigbee485TypeStr:
    DREAM_CURTAIN = "023e"
    ZIGBEE_CENTER_AC = "0292"
    ZIGBEE_FLOOR_HEARTING = "0296"
    ZIGBEE_REFRESH_AIR = "0298"
    ZIGBEE_SMART_BED = "030d"
